IC_variance_connue <- function(x_bar,sigma_square,n,alpha){
    quantile <- ... 
    IC <- ...
    IC
}

# Importation des données
data <- ... 

# Calcul de la moyenne empirique
mean <- ... 

n <- ... 
sigma_square <- ... 
alpha <- ... 

IC <- ... 

# Afficher cet intervalle
...


# Place your answer here

# Place your answer here

# Place your answer here

# Vérifier que la/les conditions sont remplies
...


degree_of_freedom <- ... 
alpha <- ... 

valeur_critique <- ... 
t_obs <- ... 
# Test pour savoir si on rejette ou non l'hypothèse nulle
...


# Vérifier que la/les conditions sont remplies
...


degree_of_freedom <- ... 
alpha <- ... 

valeur_critique <- ... 
t_obs <- ... 
# Test pour savoir si on rejette ou non l'hypothèse nulle
...


data <- data.frame(Couleur= c("Janv-Mars" , "Avr-Juin" , "Juil-Sept" , "Oct-Déc"),
                   Nombre_observé=c(110   , 57    , 53    , 80 ))

# Estimation probabilité
...


# Vérifier que la/les conditions sont remplies
...


degree_of_freedom <- ... 
alpha <- ... 

valeur_critique <- ... 
t_obs <- ... 
# Test pour savoir si on rejette ou non l'hypothèse nulle
...


# Vérifier que la/les conditions sont remplies
...


# Vérifier que la/les conditions sont remplies
...


degree_of_freedom <- ... 
alpha <- ... 

valeur_critique <- ... 
t_obs <- ... 
# Test pour savoir si on rejette ou non l'hypothèse nulle
...


data_obs <- matrix(c(50,16,31,61,26,16),nrow = 2,byrow = TRUE)
n <- sum(data_obs)

# Estimation des probabilités
...


# Calculez les nombres attendus 
...


degree_of_freedom <- ... 
alpha <- ... 

valeur_critique <- ... 
t_obs <- ... 

# Test pour savoir si on rejette ou non l'hypothèse nulle
...


regr_est <- function(data){
    
    ...

    c(alpha,beta)
}

data <- data.frame(V = c(54.3,61.8,72.4,88.7,118.6,194.0),
                    P = c(61.2,49.5,37.6,28.4,19.2,10.1))

# Estimez P
...


param <- ... 
data_trans <- ... 

s <- ... 
quantile <- ... 

# Autres valeurs à calculer ?
...


lower_bound <- ... 
upper_bound <- ... 

sprintf("L'intervalle de confiance à 95%s pour la pente de la droite du modèle de régréssion est donc [%.3f,%.3f].","%",lower_bound,upper_bound)
